### ISSUE TITLE
input type is being set to [native function]

### ISSUE THREAD

**Issue by nodeEnthu** [dima-bu/react-time-input#13]
I think you forgot to call this function on  type={this.getType} in line 124 timeInput.jsx. So the input type is being like 

input type="function () { [native code] }" class="width-max" placeholder=" " value="10:30"

```
  render () {
        return (
            <input
                name={(this.props.name)? this.props.name : undefined}
                className={this.props.className}
                type={this.getType}
                disabled={this.props.disabled}
                placeholder=" "


```

**Comment by hasnat** [comment]
Nice one, thanks for notifying about this,
https://github.com/dima-bu/react-time-input/commit/7f020eaacde857c57e289701195f32140b019183 should fix it

@dima-bu can you make sure this gets to npm

**Comment by hasnat** [comment]
I will keep this open till @dima-bu releases this to npm
