### ISSUE TITLE
Letters and special characters aren't filtered

### ISSUE THREAD

**Issue by arthurvi** [dima-bu/react-time-input#2]
Awesome component, just what I was looking for.

##### Problem
`abcd` etc. and `*()&^&@(` etc. characters are not filtered out. When I try them in the demo the component works and they are rejected/filtered, but when I use it in my own application the characters are just accepted. `isValid` is true when I use a `d` character for example. Where does the filtering for these characters take place?

**Comment by dima-bu** [comment]
Fix it
